version: '3.8'

services:
  jet_app:
    container_name: "jet_app"
    build:
        context: ./
        dockerfile: Dockerfile
    command: flask run --host=0.0.0.0 --port=8080
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped
    environment:
        - FLASK_APP=app.py
        - FLASK_ENV=development
        - FLASK_DEBUG=0
    volumes:
        - .:/usr/app